### ISSUE TITLE
Corrections re: JoinMarket and JoinInBox

### ISSUE THREAD

**Issue by Enegnei** [Enegnei/This-Month-In-Bitcoin-Privacy#3]
Pasting in comments from Waxwing via: https://bitcoinhackers.org/web/statuses/104789319086625186

> A couple of points: On the payjoin section, note what's new is BIP 78 (I don't think you linked it?), and the final sentence seems to suggest that compatibility is something still under discussion, but it is already done, at least, from spending side - so a JM user can pay a Wasabi user with this (including to Tor HS endpoint).

I linked to BIP-78 at "based on [Nicolas Dorier](https://twitter.com/NicolasDorier)’s [BIP-78](https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki)."

The part about compatibility was referring to the Samourai-Samourai and Joinmarket-Joinmarket PayJoins. I will re-write it to be more clear, I was just acknowledging that SW and JM already had PayJoin implementations, as mentioned in your release notes: "Note that the pre-existing Joinmarket-Joinmarket payjoin function still exists, but we will deprecate and remove it (almost certainly) when we add BIP78 receiver support to this wallet." And Samourai's is still not compatible.

> On the Joininbox thing: it's very misleading to describe this as a GUI for Joinmarket; we've had that for 4 years and it's vastly improved recently; see https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/JOINMARKET-QT-GUIDE.md plus various video guides linked in the readme.md. These are mostly up to date, though not 100%.

"As I covered in [TMIBP01](https://enegnei.github.io/This-Month-In-Bitcoin-Privacy/June_2020/#june-21st---introducing-joininbox), JoinInBox is a graphical interface for the CoinJoin implementation [JoinMarket](https://github.com/JoinMarket-Org/joinmarket-clientserver), currently optimized to run on the [RaspiBlitz](https://shop.fulmo.org/raspiblitz/) full node."

That sentence links to a story from [the first issue of the newsletter](https://enegnei.github.io/This-Month-In-Bitcoin-Privacy/June_2020/#june-21st---introducing-joininbox), which acknowledges that there's an existing GUI for JoinMarket and just quotes Openom's personal motivation for working on another specifically for RaspiBlitz. I will re-write and link in those docs for this newer story to make it more clear though.

> Additionally I have recently been working on a demonstration of a Javascript web/electron style cross platform client: https://x0f.org/@waxwing/104711319655673159
>
> (Also there is a Maker-in-Qt PR that has been languishing because I didn't get much positive response: https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/487 )
>
> Now, of course, what Joininbox *does* do (and is great for this) is support Maker functionality on a RPi with a graphical menu for controlling the bot; it's a stretch to call this a "GUI for Joinmarket" although technically it is, it will mislead people to say that.

ACK, I'll add those links in.

**Comment by Enegnei** [comment]
Rich diff of JM-related changes: https://github.com/Enegnei/This-Month-In-Bitcoin-Privacy/commit/6d831c88a5a3d0e4c05eb3c868c709b5fc4b2ea1?short_path=48fd52b#diff-48fd52bb33a9d690d79214f2bd425afa

Let me know if that reads better.

**Comment by AdamISZ** [comment]
Thanks for doing that, that's great, just one thing: 'recently [released](https://x0f.org/@waxwing/104711319655673159) a [JoinMarket Control Center prototype]..' - please changed that to 'recently started work on', although there was technically a 'release', that was me just testing out the binary distribution process, it's currently a very bare bones prototype.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Enegnei** [comment]
Done!
